// <auto-generated />
using System;
using BusinessAnalyticsSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessAnalyticsSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251012161930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BusinessAnalyticsSystem.Models.FinancialData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Expenses")
                        .HasColumnType("REAL");

                    b.Property<double>("FixedCosts")
                        .HasColumnType("REAL");

                    b.Property<double>("Investment")
                        .HasColumnType("REAL");

                    b.Property<double>("PricePerUnit")
                        .HasColumnType("REAL");

                    b.Property<double>("Revenue")
                        .HasColumnType("REAL");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VariableCostsPerUnit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FinancialDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
