// <auto-generated />
using System;
using BusinessAnalyticsSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessAnalyticsSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017225929_AddUsers_and_UpdateFinancialData")]
    partial class AddUsers_and_UpdateFinancialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BusinessAnalyticsSystem.Models.FinancialData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BreakEven")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("FixedCosts")
                        .HasColumnType("REAL");

                    b.Property<double>("GrossCosts")
                        .HasColumnType("REAL");

                    b.Property<double>("Investment")
                        .HasColumnType("REAL");

                    b.Property<double>("MarginPerUnit")
                        .HasColumnType("REAL");

                    b.Property<double>("PricePerUnit")
                        .HasColumnType("REAL");

                    b.Property<double>("Profit")
                        .HasColumnType("REAL");

                    b.Property<double>("ROI")
                        .HasColumnType("REAL");

                    b.Property<double>("ROS")
                        .HasColumnType("REAL");

                    b.Property<double>("Revenue")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalCosts")
                        .HasColumnType("REAL");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VariableCostPerUnit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FinancialDatas");
                });

            modelBuilder.Entity("BusinessAnalyticsSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
